### ISSUE TITLE
Get operator to pass 'operator-sdk scorecard'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/tower-operator#12]
Currently this operator doesn't have a validation section for the CRD, nor a spec CSV with CRD fields defined. I'd like to get all that fixed so this operator can pass the `operator-sdk scorecard` check.

**Comment by geerlingguy** [comment]
I know @leifmadsen has been doing a lot of work to get the scorecard check passing on some of the Ansible-based operators he's working on, so if I run into issues here, check with him also on the CoreOS slack.

**Comment by leifmadsen** [comment]
I can get mine to pass now. I'll check after lunch to see what you're missing.

**Comment by geerlingguy** [comment]
Docs for how to set up validation: https://sdk.operatorframework.io/docs/ansible/reference/advanced_options/#custom-resources-with-openapi-validation (cc @shanemcd).

**Comment by geerlingguy** [comment]
Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
