### ISSUE TITLE
Allow ingress to be configured to support TLS

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/tower-operator#13]
Currently, the Ingress resource is hardcoded to just allow access via port 80. It would be good to allow users to provide more details and/or annotations for Ingress to support HTTPS/443. See the basic TLS docs (https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) for cert support, or look into supporting cert-manager or something similar too.

**Comment by eas75034** [comment]
I created a tls secret using a self-signed cert, as I'm using tower on a private domain. I was able to add it to the ingress resource with no problem.

**Comment by geerlingguy** [comment]
@eas75034 - great! I believe it's easy enough to do (and this operator won't break it) if you do it manually as you did, but I'd also like it to be a configurable option so this operator can set it up for you too.

**Comment by geerlingguy** [comment]
Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
