### ISSUE TITLE
Avoid creating service account in default namespace

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#26]
One issue that I saw mentioned in the OpenShift issue was that the tower-operator service account gets created in the default namespace. I think it's important to break this out into its own seperate issue as I believe this will cause issues for more than just those who are running in OpenShift.

The way I see it, there are two issues that need resolved here:

**Remove namespace from Service Account creation**

https://github.com/geerlingguy/tower-operator/blob/39aec6b03ced36fb444629dedcfddc95f8e16db5/deploy/service_account.yaml#L6

and 

https://github.com/geerlingguy/tower-operator/blob/39aec6b03ced36fb444629dedcfddc95f8e16db5/deploy/tower-operator.yaml#L86

That's the easy part. The less easy part comes next.

**How do handle applying the ClusterRole to the ServiceAccount without knowing which namespace/project it is going to be created in**

https://github.com/geerlingguy/tower-operator/blob/39aec6b03ced36fb444629dedcfddc95f8e16db5/deploy/role_binding.yaml#L6-L9

and

https://github.com/geerlingguy/tower-operator/blob/39aec6b03ced36fb444629dedcfddc95f8e16db5/deploy/tower-operator.yaml#L72-L75

The answer, at this point, I think all comes down to the level of complexity you want involved in installing the operator. And this may very well become abstracted once this is hidden behind just being installed from OperatorHub -- but for now I think there are a few options:

1. **Use some templating language so users can provide their values** 

This could be done with helm or even more ansible & jinja. This will allow users to provide their values in some other file and then installation is still all done behind a single command (`helm install` or `ansible-playbook`)

2. **Patching**

This moves away from a clean, one command install -- but would give the user the ability to define their namespace in the patch command and then it would generate the appropriate yaml for where they want to actually install the operator at

ex:

```
kubectl/oc patch -f tower-operator.yaml -p '{ MY PATCH HERE }' | kubectl/oc apply -f -
```
3. **Maybe there's something better**
 
I'm not saying that the above are the only two ways. I've been playing around with a handful of other ways that haven't led anywhere at this point:
- hoping that ClusterRoleBinding would default the namespace to the current namespace context if it wasn't provided
- Trying to be tricky with the Downward API

So I think there are potentially other ways. These are more just suggestions for the short term. Again this may be a non-issue once something like OperatorHub comes into play. But for now, I think this is something that needs handled as otherwise if the user isn't installing in the `default` namespace there is a bunch of manual intervention required to get this running.

**Comment by tylerauerbeck** [comment]
This feels like it should be a solved problem as I'm sure this isn't the only operator that does things like this. So I'll continue to take a look at how this is handled elsewhere.

**Comment by tylerauerbeck** [comment]
@geerlingguy Could we take another look at this?

**Comment by geerlingguy** [comment]
@tylerauerbeck - Sorry about that, I've been neglecting this repo lately. However, I should also note that I've been working with the Ansible team on getting this project moved over to the Ansible namespace, and you may want to start moving your PRs and work over to this new repo: https://github.com/ansible/awx-operator

I haven't formally announced it yet, but I'm going to be deprecating this repo and redirecting people to the 'more official' one over there (it was forked just after the last commit to this repo).
