### ISSUE TITLE
[FEATURE REQUEST] Ansible venvs

### ISSUE THREAD

**Issue by stobias123** [geerlingguy/tower-operator#27]
Some modules require additional pip packages to be installed. Managing `venvs` isn't really possible from what I can tell thus far within the operator, and I think that type of management is perfect for this operator.

I thought this might be a good issue for me to help contribute on, but didn't want to surprise PR without discussing how this should be implemented.

With that said, any thoughts or preferences on how to implement? Should users just create their own tower container from the tower base image? Should the operator leverage init containers to install python dependencies and venvs at boot?

**Comment by geerlingguy** [comment]
@stobias123 - I would imagine the best solution would be for users to customize the Tower image themselves (e.g. `create their own tower container from the tower base image`). The alternative is to have this operator manage python environments _inside_ the running tower containers, which I think would be a bit antithetical to the idea of running Tower in a container (you shouldn't mutate the state of the contained application outside of that application's own mechanisms).
