### ISSUE TITLE
Automate Ansible Tower license

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#31]
Right now, the operator seems to spin up Ansible Tower -- but it's still a manual process to apply the license. Would applying the license be something we could see adding to this operator?

**Comment by geerlingguy** [comment]
@tylerauerbeck - That would be nice to be able to do; I just don't know the best mechanism for doing so. Maybe a secret mounted into a directory that could be referenced and loaded in once Tower is running?

I don't know if there's actually any way to specify a license outside of the admin UI workflow—that's [all I can find documented](https://docs.ansible.com/ansible-tower/latest/html/quickstart/import_license.html) in the docs :/

**Comment by tylerauerbeck** [comment]
This can actually be done via the API and we've got a role that does that here: https://github.com/redhat-cop/infra-ansible/tree/master/roles/ansible/tower/config-ansible-tower-license

Happy to help roll this into the operator. Just wasn't sure where this operator was looking to draw the line. My thought would be to use a secret like you mention though. I think the thing to think about though may be what happens when you want to update your license. Happy to get the initial functionality added though if you'd be willing to have it.

**Comment by geerlingguy** [comment]
(Note that this issue might not be a fit for the awx operator either, as it's focus seems to be shifting to AWX-first and will only 'experimentally' support Tower until there's an officially supported Tower operator.

Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
