### ISSUE TITLE
Switch to k8s_info from k8s_facts

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#32]
Ansible is switching the `k8s_facts` module to `k8s_info`. Should eventually look to update this prior to deprecation.

```
[DEPRECATION WARNING]: The 'k8s_facts' module has been renamed to 'k8s_info'. 
This feature will be removed in version 2.13. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by geerlingguy** [comment]
Heh, I have a TODO in the code for this: https://github.com/geerlingguy/tower-operator/blob/27b8ba968ebd1374d7dff5532f96e3fc94a2d2ea/roles/tower/tasks/main.yml#L15

Was waiting for the operator base image to be upgraded to Ansible 2.9. I guess that's the case now?
