### ISSUE TITLE
Create a contributors guide

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#33]
Would be good to have a contributors guide so that folks could understand what kind of guidelines there are for getting involved here.

For example, not sure what (if any) version numbers I should be bumping in any of the docs as I look to add OpenShift functionality. Or even if maybe this is something to look to add to any of the automation (Travis, GitHub Actions, etc.)

**Comment by geerlingguy** [comment]
Not stale.

**Comment by geerlingguy** [comment]
Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
