### ISSUE TITLE
Prepare for AWX/Tower new versions using Redis instead of RabbitMQ

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/tower-operator#39]
The latest versions (3.7.0 / 10(?).0.0) will soon be using Redis instead of RabbitMQ; more info here: https://github.com/ansible/awx/issues/5443

Docker Compose changes: https://github.com/ansible/awx/pull/6034/files#diff-ee215160a0808b30b25efa63ca9ac0f9

Kubernetes role changes:

  - https://github.com/ansible/awx/pull/6034/files#diff-88fadd046eb3187e4500687368abc149
  - https://github.com/ansible/awx/pull/6034/files#diff-497ab200c9d7364c4f7d16bb0dccea4a
  - https://github.com/ansible/awx/pull/6034/files#diff-fcdf2a94816826e08fc58165d9b14e53
  - https://github.com/ansible/awx/pull/6034/files#diff-d4821350fbf4720a93df5d911e726f61
  - https://github.com/ansible/awx/pull/6034/files#diff-642b14a5fd9b35b514e48a19b448c27f
  - https://github.com/ansible/awx/pull/6034/files#diff-c714c2f39ebfa25d09512440f300060f
  - https://github.com/ansible/awx/pull/6034/files#diff-1d0344bd8aaa1e7b8c49214f37dc8414

Though some have run into issues (see https://github.com/ansible/awx/issues/6365) — so for this operator it may be prudent to wait a little.

**Comment by fabiocruzcoelho** [comment]
Hello,

Any predictions of when this operator will be updated for use with Redis?

**Comment by geerlingguy** [comment]
@fabiocruzcoelho - I will likely wait until closer to or after Ansible Tower 3.7 is released.

**Comment by geerlingguy** [comment]
Marking as duplicate of #42 — moving discussion there.
