### ISSUE TITLE
Ability to use external postgres database

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#47]
In some use cases, I"d like to only run Tower/AWX inside the cluster, but rely on an external set of postgres databases that I'm already operatoring. As part of the operator, I'd like to be able to point to this database instead of spinning one up in the cluster.

**Comment by geerlingguy** [comment]
Agreed, that would be a nice feature. I do something like this in my Drupal operator, so you can use an external database (whether in cluster or elsewhere): https://github.com/geerlingguy/drupal-operator/blob/master/roles/drupal/tasks/database.yml#L2-L4

**Comment by geerlingguy** [comment]
Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
