### ISSUE TITLE
Clustered / High Availability Tower

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#48]
It would be nice to be able to run a clustered set of towers as part of this operator as mentioned here: https://docs.ansible.com/ansible-tower/latest/html/administration/clustering.html.

**Comment by geerlingguy** [comment]
Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
