### ISSUE TITLE
Support LDAP configuration with custom CA

### ISSUE THREAD

**Issue by tylerauerbeck** [geerlingguy/tower-operator#49]
If you attempt to configure LDAP authentication that is backed by a custom (non-trusted) CA, you'll see the following error:

```bash
2020-06-09 17:21:22,693 WARNING  django_auth_ldap Caught LDAPError while authenticating test-user: SERVER_DOWN({'desc': "Can't contact LDAP server", 'info': 'error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (self signed certificate in certificate chain)'},)
```

It would be useful to be able to attach custom CA's via the CR that is created that would resolve this issue.

**Comment by tylerauerbeck** [comment]
Looks like we should be able to steal the logic recommended here and have the operator work some magic: https://access.redhat.com/solutions/4934891

**Comment by geerlingguy** [comment]
Now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore (as I consider it a historic artifact which was used to as a base for the ansible-namespace version, and I'm redirecting all issues and PRs to the Ansible-maintained version: https://github.com/ansible/awx-operator
