### ISSUE TITLE
Operator Inoperable after breaking change upstream

### ISSUE THREAD

**Issue by Mercwri** [geerlingguy/tower-operator#53]
I attempted to stand up an instance today and Operator failed to deploy due to being unable to pull the container ansible/tower-operator:0.4.0

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  <unknown>         default-scheduler  Successfully assigned default/tower-operator-67bb7f6b8b-5gb4j to node2
  Warning  Failed     16s               kubelet, node2     Error: ImagePullBackOff
  Normal   BackOff    16s               kubelet, node2     Back-off pulling image "ansible/tower-operator:0.4.0"
  Warning  Failed     2s (x2 over 17s)  kubelet, node2     Failed to pull image "ansible/tower-operator:0.4.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for ansible/tower-operator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     2s (x2 over 17s)  kubelet, node2     Error: ErrImagePull
```
I tried updating the image to awx-operator but the operator (after it deploys) does not create an awx deployment or pgsql deployment.

**Comment by geerlingguy** [comment]
It looks like as a result of https://github.com/ansible/awx-operator/pull/4, the image which was available as 'tower-operator' was moved to https://hub.docker.com/r/ansible/awx-operator and the old image was removed, breaking any existing installs :/

The quickest fix would be to change your operator deployment image to the new awx-operator image.

Also just wanted to note that now that the operator is being maintained in the Ansible namespace, I am not going to maintain this project anymore, and redirect any issues and further development to the Ansible-maintained version: https://github.com/ansible/awx-operator
